# Generated by Django 5.1.1 on 2024-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersi', '0004_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='prestatire',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
