# Generated by Django 5.1.1 on 2024-11-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersi', '0005_remove_user_is_approved_prestatire_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatire',
            old_name='presentation',
            new_name='Service',
        ),
        migrations.RemoveField(
            model_name='prestatire',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='designation',
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
